### ISSUE TITLE
ejs file not getting called in html

### ISSUE THREAD

**Issue by vaishalidjoshi** [samsprakash/tutorials#1]
hi 
while i am calling ejs files in index.html using div tag it is not getting called.
any specific reason?
do i need to do any setting?

**Comment by vaishalidjoshi** [comment]
<!doctype html>
<html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Canjs</title>
      <link rel="stylesheet" href="css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <h1>Contact Manager</h1>
            <hr \>
            <div class="page">
                 <div id="contactList"></div>
                 <div id="createForm"></div>
            </div>
        </div>

```
    <script type="text/javascript" src="js/jquery-3.0.0.min.js"></script>
    <script src="js/can.jquery.js"></script>
    <script src="js/can.fixture.js"></script>
    <script src="js/contact.js"></script>   

</body>
```

</html> 

<a href="#/new" class="btn btn-primary add">Add Contact</a>

<hr />

<table class="table striped">
    <thead>
        <tr> 
            <th>Name</th><th>Email</th><th>Phone</th><th>Address</th>
        </tr>
    </thead>
    <tbody>
        <% list(contacts, function(contact){ %>
            <tr>
                <td> <%= contact.name %></td>
                <td> <%= contact.email %></td>
                <td> <%= contact.phone %></td>
                <td> <%= contact.address %></td>
                <td><button type="button" class="btn btn-primary edit" value="<%= contact.id %>">Edit</button></td>
            </tr>
        <% }) %>
    </tbody>
</table>

**Comment by samsprakash** [comment]
You need to have json files to display the contact

**Comment by vaishalidjoshi** [comment]
Hi
But in code json files not included? From where I will ger it?

**Comment by vaishalidjoshi** [comment]
hi,
 I am new to this canjs. can you let me know how this code will work? as i am not getting JSON files?

**Comment by samsprakash** [comment]
Right now I am using fixtures to get the josn object.. Please follow this instruction.. This is my blog.. http://ilearnhub.in/canjs-sample-application/ ..Make sure that you need to run the code in server. Like http://localhost.. Since it is user to get the details from get request and post request from the server..

**Comment by vaishalidjoshi** [comment]
Hi,
 Thanks for the reply.
I downloaded your code and have put into C:\inetpub\wwwroot

and then callled http://localhost/index.html

but it doesn't load data

anything else i need to do?

Regards
Vaishali

**Comment by samsprakash** [comment]
What is the error you are getting in browser console?

**Comment by vaishalidjoshi** [comment]
i don't get error only
Header get printed ie 'CONTACT MANAGER'

nothing else

**Comment by samsprakash** [comment]
Debug the contact.js.. I am not sure why you are getting this issue
